root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/pingbot"
  cmd = "make build BINARY_OUT=./tmp/pingbot"
  delay = 1000
  exclude_dir = ["tmp"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "toml"]
  kill_delay = "0s"
  log = "air-build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
