project_name: pingbot

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
    goarch:
      - amd64

    binary: '{{ .ProjectName }}.out'

    ldflags:
      - -s -w
      - -X gitlab.com/gaming0skar123/go/pingbot/config.Version={{.RawVersion}}
      - -X gitlab.com/gaming0skar123/go/pingbot/config.Build={{.Date}}

archives:
  - format: tar.gz

    files:
      - .env.schema
      - config.schema.toml
      - README.md
      - LICENSE

checksum:
  name_template: 'md5_checksums.txt'

  algorithm: md5
