name: Lint

on: [pull_request, push]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: GolangCi Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
